name: flutter_feathersjs
description: Communicate with your feathers js server from flutter.
version: 4.0.0-dev.nullsafety
homepage: https://github.com/Dahkenangnon/flutter_feathersjs.dart
repository: https://github.com/Dahkenangnon/flutter_feathersjs.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Socketio client
  socket_io_client: ^1.0.1
  # Http client
  dio: ^4.0.0
  # For storing the acces token
  shared_preferences: ^2.0.6
  meta: ^1.3.0
  # Event managment
  event_bus: ^2.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: