name: flutter_feathersjs
description: Communicate with your feathers js server from flutter.
version: 2.0.2-dev
homepage: https://github.com/Dahkenangnon/flutter_feathersjs.dart
repository: https://github.com/Dahkenangnon/flutter_feathersjs.dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Socketio client
  socket_io_client: ^0.9.12
  # Http client
  dio: ^4.0.0
  # For storing the acces token
  shared_preferences: ^2.0.5
  meta: ^1.1.8
  # Event managment
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
