name: feathersjs
description: Feathers Js client for flutter app.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Socketio client
  socket_io_client: ^0.9.9
  # Http client
  dio: ^3.0.9
  # For storing the acces token
  shared_preferences: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
