name: flutter_feathersjs
description: Communicate with your feathers js server from flutter.
version: 0.1.0
homepage: https://github.com/Dahkenangnon/flutter_feathersjs.dart
repository: https://github.com/Dahkenangnon/flutter_feathersjs.dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Socketio client
  socket_io_client: ^0.9.9
  # Http client
  dio: ^3.0.9
  # For storing the acces token
  shared_preferences: ^0.5.12+2
  meta: ^1.1.8
  # Event managment
  event_bus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
