name: flutter_feathersjs
description: Communicate with your feathers js  server from flutter app with unbelieved ease and make happy your customers.
version: 4.0.5
homepage: https://github.com/Dahkenangnon/flutter_feathersjs.dart
repository: https://github.com/Dahkenangnon/flutter_feathersjs.dart
documentation: https://dahkenangnon.github.io/flutter_feathersjs.dart/
issue_tracker: https://github.com/Dahkenangnon/flutter_feathersjs.dart/issues


environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  socket_io_client: ^2.0.0

  dio: ^4.0.6

  shared_preferences: ^2.0.15

  event_bus: ^2.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
